--
-- PostgreSQL database dump
--

\restrict MWbaiUgUwdGAFuLwIKImFTDDqA7ZzS80fCAWHCyeEGgQP8PdYYaFyhYgfDhtB93

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: songs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.songs (
    id bigint NOT NULL,
    singer character varying(255),
    composer character varying(255),
    image_url text,
    lyricist character varying(255),
    movie character varying(255),
    song_name character varying(255) NOT NULL,
    song_url text,
    actor character varying(255),
    actress character varying(255),
    category character varying(255),
    artist character varying(255)
);


ALTER TABLE public.songs OWNER TO postgres;

--
-- Name: songs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.songs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.songs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_hidden_songs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_hidden_songs (
    user_id bigint NOT NULL,
    song_id bigint NOT NULL
);


ALTER TABLE public.user_hidden_songs OWNER TO postgres;

--
-- Name: user_liked_songs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_liked_songs (
    user_id bigint NOT NULL,
    song_id bigint NOT NULL
);


ALTER TABLE public.user_liked_songs OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(20) DEFAULT 'USER'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Data for Name: songs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.songs (id, singer, composer, image_url, lyricist, movie, song_name, song_url, actor, actress, category, artist) FROM stdin;
1	KK	Pritam	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769962528/zara_sa_lj2app.jpg	Sayeed Quadri	Jannat	Zara Sa	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968448/Zara_Sa_n1w1ip.mp3	Emraan Hashmi	Sonal Chauhan	Romantic	\N
2	Vishal Dadlani	Ram Sampath	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769962499/Jee_le_zara_ylcjsz.jpg	Javed Akhtar	Talaash	Jee Le Zara	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968397/Jee_Le_Zaraa_-_Talaash_320_Kbps_h45g82.mp3	Aamir Khan	Kareena Kapoor, Rani Mukerji	Romantic	\N
3	Mustafa Zahid	Pritam	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769962547/tera_mera_rishta_hxlqbq.jpg	Sayeed Quadri	Awarapan	Tera Mera Rishta	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968501/Tera_Mera_Rishta_xxt5wc.mp3	Emraan Hashmi	Shriya Saran	Romantic	\N
4	Mohit Chauhan	Pritam	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769962535/Tum_se_hi_pvrkh6.jpg	Irshad Kamil	Jab We Met	Tum Se Hi	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968470/Tum_Se_Hi_n2xiht.mp3	Shahid Kapoor	Kareena Kapoor	Romantic	\N
5	Atif Aslam	Atif Aslam	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769962505/kuch_is_tarahh_zaqodb.jpg	Sameer	Doorie (Album)	Kuch Is Tarah	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968404/Kuchh_Is_Tarah_-_8_X_10_Tasveer_320_Kbps_ng4uei.mp3	\N	\N	Romantic	\N
7	KK	Pritam	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769962490/Jannatein_kaha_buvgvd.jpg	Sayeed Quadri	Jannat 2	Jannatein Kahan	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968390/Jannatein_Kahan_Power_Ballad_-_Jannat_2_320_Kbps_1_zwsjxw.mp3	Emraan Hashmi	Esha Gupta	Romantic	\N
8	Shafqat Amanat Ali	Pritam	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769962485/Jaavedan_Hai_tz3nnn.jpg	Sayeed Quadri	Murder 3	Jaavedan Hai	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968383/Jaavedaan_Hai_Lyrical_Video___1920_Evil_Returns___KK_Suzanne_D_Mello_oww6d2.m4a	Randeep Hooda	Aditi Rao Hydari, Sara Loren	Romantic	\N
9	Ami Mishra	Ami Mishra	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769962479/Hasi_g2torn.jpg	Kunaal Vermaa	Hamari Adhuri Kahani	Hasi	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968375/Hasi_Male_Version_-_Hamari_Adhuri_Kahani_320_Kbps_dfegif.mp3	Emraan Hashmi	Vidya Balan	Romantic	\N
10	Arijit Singh	Mithoon	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769962441/Hai_dil_ye_mera_ugcbpe.jpg	Sayeed Quadri	Hate Story 2	Hai Dil Ye Mera	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968344/Hai_Dil_Ye_Mera_eytk5i.mp3	Jay Bhanushali	Surveen Chawla	Romantic	\N
11	KK	Pritam	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769962426/dil_ibadat_h0wf0k.jpg	Sayeed Quadri	Tum Mile	Dil Ibaadat	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968351/Dil_Ibaadat_qjcnog.mp3	Emraan Hashmi	Soha Ali Khan	Romantic	\N
12	Javed Ali	Rashid Khan	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769962409/Deewana_kar_raha_hai_brmzbm.jpg	Sanjay Masoomm	Raaz 3	Deewana Kar Raha Hai	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968337/Deewana_Kar_Raha_Hai_ng7v3b.mp3	Emraan Hashmi	Esha Gupta	Romantic	\N
140	\N	Pritam	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779910025/musiverse/covers/pvtgungsnyvlmks0djwm.jpg	Amitabh Bhattacharya	Dangal	Naina	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779897000/Naina_Dangal.mp3	Aamir Khan	Sakshi Tanwar	Bollywood Romantic	Arijit Singh
6	Arijit Singh	Jeet Gannguli	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779910048/musiverse/covers/euicedr3hiemgf6eslhf.jpg	Kausar Munir	Raaz Reboot	Lo Maan Liya	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968412/Lo_Maan_Liya_-_Raaz_Reboot_320_Kbps_teitnx.mp3	Emraan Hashmi	Kriti Kharbanda	Romantic	\N
147	\N	Pritam	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779910062/musiverse/covers/tfmorzuvgdcqovdnhvia.jpg	Mayur Puri	Race 2	Be Intehaan	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961423/Be_Intehaan_-_Lyrical_Video___Race_2___Saif_Ali_Khan_Deepika_Padukone___Atif_Aslam___Pritam___Tips_js8z0e.mp3	Saif Ali Khan	Deepika Padukone	Romantic	Atif Aslam, Sunidhi Chauhan
97	\N	Gajendra Verma 	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779905066/oed4gdp8m1olbo0gqoon.jpg	Assem Ahmed 	Table No. 21	Mann Mera	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779905063/f6n7zdzolx2vtk6gksgw.mp3	Rajeev Khandelwal 	Paoli Dam 	Pop	Gajendra Verma 
98	\N	Sanjay Leela Bhansali	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769964122/deewani_mastani_yoyusg.jpg	Siddharth-Garima	Bajirao Mastani	Deewani Mastani	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779899769/Deewani_Mastani_-_Bajirao_Mastani_320_Kbps_cvubs7.mp3	Ranveer Singh	Deepika Padukone, Priyanka Chopra	Classic	Shreya Ghoshal, Ganesh Chandanshive, Mujtaba Aziz Naza, Farhan Sabri, Altmash Faridi
99	\N	Vishal-Shekhar	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769964115/manwa_laage_w2yfj3.jpg	Irshad Kamil	Happy New Year	Manwa Laage	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779899778/Manwa_Laage_-_Happy_New_Year_320_Kbps_vxqzll.mp3	Shah Rukh Khan	Deepika Padukone	Classic	Arijit Singh, Shreya Ghoshal
100	\N	Pritam	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769964094/Saudebaazi_Encore_atv45e.jpg	Irshad Kamil	Aakrosh	Saudebaazi	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779899796/saudebaazi_pgth5l.mp3	Ajay Devgn, Akshaye Khanna	Bipasha Basu	Classic	Anupam Amod
101	\N	A. R. Rahman	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769964087/tere_bina_xyjui5.jpg	Gulzar	Guru	Tere Bina	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779899820/Tere_Bina_-_Guru_320_Kbps_ypzapd.mp3	Abhishek Bachchan	Aishwarya Rai Bachchan	Classic	A. R. Rahman, Chinmayi Sripaada, Murtuza Khan, Qadir Khan
102	\N	A. R. Rahman	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779898640/tum_tak_dbz8mg.jpg	Irshad Kamil	Raanjhanaa	Tum Tak	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779899839/Tum_Tak_-_Raanjhanaa_320_Kbps_uwdwcs.mp3	Dhanush	Sonam Kapoor	Classic	Javed Ali, Keerthi Sagathia, Pooja AV
103	\N	Stephen Sanchez, Ian Fitchuk	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769964084/Until-I-Found-You-Em-Beihold-Version-English_txl4vd.jpg	Stephen Sanchez, Em Beihold		Until I Found You	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769962116/Stephen_Sanchez_-_Until_I_Found_You_Official_Video_g6wbap.mp3			Classic	Stephen Sanchez
104	\N	Rami Yacoub, Carl Falk	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769964082/whatmakesyoubeautiful_dqfgkh.jpg	Savan Kotecha		What Makes You Beautiful	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769962121/One_Direction_-_What_Makes_You_Beautiful_Official_Video_tvupwe.mp3			Classic	One Direction
105	\N	Ed Sheeran, Steve Mac	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769964092/Perfect_gcxlvz.jpg	Ed Sheeran		Perfect	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769962131/Ed_Sheeran_-_Perfect_Official_Music_Video_flzpti.mp3			Classic	Ed Sheeran
106	\N	Jamie Scott, Julian Bunetta, John Ryan	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769964097/One_Direction_-_Night_Changes_Single_Cover_wcidw0.png	Jamie Scott, Julian Bunetta, John Ryan		Night Changes	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769962126/One_Direction_-_Night_Changes_onxwms.mp3			Classic	One Direction
107	\N	Andrew Choi, MZMC, Otha 'Vakseen' Davis III	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963604/beyourlight_ynrxjm.jpg	Kim Eana	The Story of Light EP.2	Be Your Light	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961930/Be_Your_Light_%E5%81%B7%E5%81%B7%E8%97%8F%E4%B8%8D%E4%BD%8F_%E9%9B%BB%E8%A6%96%E5%8A%87%E6%8F%92%E6%9B%B2_-_%E9%A6%AC%E4%BC%AF%E9%A8%AB_%E6%BC%AB%E5%A4%A9%E8%8A%B1%E7%93%A3%E5%9C%A8%E6%88%91%E5%80%91%E8%BA%AB%E5%BE%8C_%E8%B7%9F%E9%9A%A8_%E6%98%AF%E5%A6%B3%E6%89%8D_%E8%AE%93_%E9%99%BD%E5%85%89%E8%90%BD%E4%B8%8B%E4%BE%86_%E5%8B%95%E6%85%8B%E6%AD%8C%E8%A9%9E_mght05.mp3	N/A	N/A	Korean	SHINee
108	\N	Joji, Clams Casino, Thundercat	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963609/Cant_get_over_you_z0xzpl.jpg	Joji	BALLADS 1	Can't Get Over You	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961945/-MV-_Paul_Kim_%ED%8F%B4%ED%82%B4_-_Can_t_Get_Over_You_%EC%A2%8B%EC%95%84%ED%95%B4%EC%9A%94_tbvqrd.mp3	N/A	N/A	Korean	Joji
109	\N	Adam von Mentzer, Mac Felländer-Tsai, Louise Udin	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963590/cupid_wl4gut.jpg	Keena	The Beginning: Cupid	Cupid	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961896/FIFTY_FIFTY_%ED%94%BC%ED%94%84%ED%8B%B0%ED%94%BC%ED%94%84%ED%8B%B0_-__Cupid__Official_MV_iv0uki.mp3	N/A	N/A	Korean	FIFTY FIFTY
110	\N	Lee Hae-ri, Kang Min-kyung	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963593/Forgetting_you_eqoiky.jpg	Various	K-Drama OST	Forgetting You	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961883/Forgetting_You_%EA%B7%B8%EB%8C%80%EB%A5%BC_%EC%9E%8A%EB%8A%94%EB%8B%A4%EB%8A%94_%EA%B1%B4_-_Davichi_%EB%8B%A4%EB%B9%84%EC%B9%98_-HAN_ROM_ENG_COLOR_CODED_LYRICS-_ko5brj.mp3	N/A	N/A	Korean	Davichi
111	\N	Park Se-joon, Seo Dong-hwan	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963601/Here_always_mfgqlx.jpg	Kim Na-young	Hometown Cha-Cha-Cha OST Part 3	Here Always	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961959/-Hometown_Chachacha_OST_Part_7_ENGSUB-__Here_Always__by_Stray_Kids_%EC%8A%B9%EB%AF%BC_FMV_-1x14_bmly4l.mp3	Kim Seon-ho	Shin Min-a	Korean	Seungmin (Stray Kids)
112	\N	DOKO	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963595/I_m_missing_you_peal1q.jpg	DOKO	True Beauty OST	I'm Missing You	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961877/Sunjae_%EC%84%A0%EC%9E%AC__I_m_Missing_You__-OST-_%EC%97%AC%EC%8B%A0%EA%B0%95%EB%A6%BC_OST_Part_4_-MV-_jgprfu.mp3	Cha Eun-woo	Moon Ga-young	Korean	Sunjae
113	\N	Kim Do-hoon	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963599/Last_chance_zrecym.jpg	Various	The Moon That Embraces the Sun OST	Last Chance	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961922/-MV-_So_Soo_Bin_%EC%86%8C%EC%88%98%EB%B9%88_-_Last_Chance_necn03.mp3	Kim Soo-hyun	Han Ga-in	Korean	K.Will
114	\N	Nam Hye-seung	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963612/Love_you_with_all_my_heart_cfcipd.jpg	Kim Kyung-hee	Queen of Tears OST	Love You With All My Heart	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961950/-MV-_Crush_-_Love_You_With_All_My_Heart_%EB%AF%B8%EC%95%88%ED%95%B4_%EB%AF%B8%EC%9B%8C%ED%95%B4_%EC%82%AC%EB%9E%91%ED%95%B4_rgqolu.mp3	Kim Soo-hyun	Kim Ji-won	Korean	Crush
115	\N	Kwon Deok-geun	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963618/Reasons_of_my_smiles_awdah2.jpg	Kang Eun-kyung	Queen of Tears OST Part 1	Reasons of My Smiles	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961955/-MV-_BSS_%EB%B6%80%EC%84%9D%EC%88%9C_SEVENTEEN_-_The_Reasons_of_My_Smiles_%EC%9E%90%EA%BE%B8%EB%A7%8C_%EC%9B%83%EA%B2%8C_%EB%8F%BC_fai9qg.mp3	Kim Soo-hyun	Kim Ji-won	Korean	BSS (SEVENTEEN)
116	\N	Rocoberry	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963616/Stay_with_me_p8wjgu.jpg	Lee Seung-joo	Goblin OST Part 1	Stay With Me	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779898172/CHANYEOL_Punch_-_Stay_With_Me_Lyrics_easy_lyrics_nt8vft.m4a	Gong Yoo	Kim Go-eun	Korean	Chanyeol & Punch
117	\N	Rocoberry	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963606/With_you_xlxkyl.jpg	Jihoon (Rocoberry)	Our Blues OST Part 4	With You	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961937/-MV-_%EC%A7%80%EB%AF%BC_Jimin_X_%ED%95%98%EC%84%B1%EC%9A%B4_Ha_Sung-Woon_-_With_you___%EC%9A%B0%EB%A6%AC%EB%93%A4%EC%9D%98_%EB%B8%94%EB%A3%A8%EC%8A%A4_Our_Blues_OST_Part_4_r6eg0j.mp3	Lee Byung-hun	Shin Min-a	Korean	Jimin & Ha Sung-woon
118	\N	Amaal Mallik	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963992/Besabriyaan_x0rchm.jpg	Manoj Muntashir	M.S. Dhoni: The Untold Story	Besabriyaan	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779897120/Besabriyaan_-_M.S._Dhoni_-_The_Untold_Story_320_Kbps_nw0z9s.mp3	Sushant Singh Rajput	Kiara Advani	Motivational	Armaan Malik
119	\N	Sachin-Jigar	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769964002/Ek_zindagi_kj7z4w.jpg	Jigar Saraiya	Angrezi Medium	Ek Zindagi	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779897128/Ek_Zindagi_-_Angrezi_Medium_320_Kbps_eqwbih.mp3	Irrfan Khan	Radhika Madan	Motivational	Tanishkaa Sanghvi, Sachin-Jigar
120	\N	Shantanu Moitra	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963995/give_me_some_sunshine_sq8fpg.jpg	Swanand Kirkire	3 Idiots	Give Me Some Sunshine	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779897142/Give_Me_Some_Sunshine_-_Raag.Fm_ignn4a.mp3	Aamir Khan, Sharman Joshi, R. Madhavan	Kareena Kapoor	Motivational	Suraj Jagan, Sharman Joshi
121	\N	Jasleen Royal	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963999/khol_de_par_b3ibwd.jpg	Raj Shekhar	Hichki	Khol De Par	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779897160/Khol_De_Par_-_Hichki_320_Kbps_rl74cw.mp3	N/A	Rani Mukerji	Motivational	Arijit Singh
122	\N	Amit Trivedi	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769964004/love_you_zindagi_graocb.jpg	Kausar Munir	Dear Zindagi	Love You Zindagi	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779897171/Love_You_Zindagi_-_Dear_Zindagi_320_Kbps_szsqix.mp3	Shah Rukh Khan	Alia Bhatt	Motivational	Jasleen Royal, Amit Trivedi
123	\N	Sohail Sen	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769964007/Mera_safar_xfamwt.jpg	Jamil Ahmed	Baazaar	Mera Safar	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779897181/Mera_Safar_Iqlipse_Nova_320_Kbps_cpq7gl.mp3	Saif Ali Khan	Radhika Apte	Motivational	Sohail Sen
124	\N	Avvy Sra	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963273/Ve_haaniyan_ncwlv9.jpg	Sagar	N/A	Ve Haaniyaan	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779893292/Ve_Haaniyaan_-_Avvy_Sra_320_Kbps_1_pgb6hv.mp3	Ravi Dubey	Sargun Mehta	Punjabi	Danny Ft. Avvy Sra
125	\N	Silver Coin	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963275/teri_aa_jatta_ggtdxv.jpg	Daljit Chitti	N/A	Teri Aa Jatta	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779893311/Teri_Aa_Jatta_-_Guntaj_320_MyMp3Song_1_kdsaft.mp3	Guntaj	Sruishty Maan	Punjabi	Guntaj
126	\N	MixSingh	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963277/suniyan_suniyan_ob6lf7.webp	Juss	N/A	Suniyan Suniyan	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779893316/Suniyan_Suniyan_-_Juss_320_Kbps_1_jtghnd.mp3	Juss	N/A	Punjabi	Juss
127	\N	Tanishk Bagchi	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963284/Raatan_lambiyan_sedye4.jpg	Tanishk Bagchi	Shershaah	Raataan Lambiyan	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779891721/Raataan_Lambiyan_-_Shershaah_320_Kbps_dbjhzt.mp3	Sidharth Malhotra	Kiara Advani	Punjabi	Jubin Nautiyal, Asees Kaur
128	\N	Shubh	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779893583/One_Love_n9pqhn.jpg	Shubh	No Love EP	One Love	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779891718/One_Love_-_Shubh_320_Kbps_nbbzee.mp3	Shubh	N/A	Punjabi	Shubh
129	\N	Jasleen Royal	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963282/ranjha_ccvbe9.jpg	Anvita Dutt	Shershaah	Ranjha	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779891728/Ranjha_-_Shershaah_320_Kbps_m1gh3o.mp3	Sidharth Malhotra	Kiara Advani	Punjabi	Jasleen Royal, B Praak
130	\N	Ikky	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963280/Softly_xtbvg7.jpg	Karan Aujla	Making Memories	Softly	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779891734/Softly_-_Making_Memories_320_Kbps_xjy5gn.mp3	Karan Aujla	Tanu Grewal	Punjabi	Karan Aujla
131	\N	Intense	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779893718/excuses_song_qjicp7.jpg	Gurinder Gill	Not by Chance	Excuses	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779891538/Excuses_320_PagalWorld.com.sb_.mp3.crdownload_bcbmyh.mp3	A.P. Dhillon	N/A	Punjabi	A.P. Dhillon, Gurinder Gill
132	\N	Satinder Sartaaj	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779893842/ikko_mikke_nu4bt5.jpg	Satinder Sartaaj	Ikko Mikke	Ikko Mikke	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779891588/Ikko_-_Mikke_-_Title_Track_320_Kbps_gkvwrm.mp3	Satinder Sartaaj	Aditi Sharma	Punjabi	Satinder Sartaaj
133	\N	Jaani	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779893930/jhaanjar_dvcjxb.jpg	Jaani	Honeymoon	Jhaanjar	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779891647/Jhaanjar_-_B_Praak_320_Kbps_kml1ol.mp3	Gippy Grewal	Jasmin Bhasin	Punjabi	B Praak
134	\N	Sachet-Parampara	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779894109/mayya_mainu_uzuzlo.jpg	Shellee	Jersey	Maiyya Mainu	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961592/Maiyya_Mainu_-_Lyrical___Jersey___Shahid_Kapoor_Mrunal_Thakur__Sachet-Parampara__Shellee___Gowtam_T_hkiyle.mp3	Shahid Kapoor	Mrunal Thakur	Punjabi	Sachet Tandon
135	\N	B Praak	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779894008/mann_bhar_xersip.jpg	Jaani	Shershaah	Mann Bharrya	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779891710/Mann_Bharryaa_2.0_-_Shershaah_320_Kbps_kxvypu.mp3	Sidharth Malhotra	Kiara Advani	Punjabi	B Praak
136	\N	Shankar-Ehsaan-Loy	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963380/128Salaam-E-Ishq_-_Salaam-E-Ishq_kfymgl.jpg	Sameer	Salaam-E-Ishq	Salaam-E-Ishq	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779895708/Salaam-E-Ishq_zhkhwi.mp3	Salman Khan, John Abraham, Anil Kapoor	Priyanka Chopra, Vidya Balan, Juhi Chawla	Bollywood Pop	Sonu Nigam, Shreya Ghoshal, Kunal Ganjawala, Sadhana Sargam
137	\N	Sachin-Jigar	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963412/aayi-nai-stree-2_mx62ho.jpg	Amitabh Bhattacharya	Stree 2	Aayi Nai	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779896452/Aayi_Nai_-_Stree_2_320_Kbps_tqevqc.mp3	Rajkummar Rao	Shraddha Kapoor	Bollywood Pop	Pawan Singh, Simran Choudhary, Divya Kumar
138	\N	Sia, Greg Kurstin	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963409/cheapthrills_swvobr.jpg	Sia Furler, Greg Kurstin	N/A	Cheap Thrills	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961683/Sia_-_Cheap_Thrills_Lyrics_ft._Sean_Paul_my6fq1.mp3	N/A	N/A	Pop	Sia, Sean Paul
139	\N	Taylor Swift, Jack Antonoff, St. Vincent	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963366/cruel_summer_joluci.jpg	Taylor Swift, Jack Antonoff, St. Vincent	N/A	Cruel Summer	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961675/Taylor_Swift_-_Cruel_Summer_Official_Audio_pybqkr.mp3	N/A	N/A	Pop	Taylor Swift
141	\N	Ed Sheeran, Steve Mac, Johnny McDaid	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963407/shape_of_you_1_c45jhb.png	Ed Sheeran, Steve Mac, Johnny McDaid	N/A	Shape of You	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779895698/Shape_of_You-_PagalSongs.Com.IN_qzxgat.mp3	N/A	N/A	Pop	Ed Sheeran
142	\N	Justin Bieber, Julia Michaels, Justin Tranter, Skrillex, BloodPop	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963397/sorry_justin_ymzzfx.jpg	Justin Bieber, Julia Michaels, Justin Tranter	N/A	Sorry	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779895595/Sorry_320_PagalWorld.com.so_xhn2yu.mp3	N/A	N/A	Pop	Justin Bieber
143	\N	Charlton Howard, Justin Bieber, Cashmere Cat, Charlie Puth, Blake Slatkin	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963422/Stay-English-2021_rbg8bn.jpg	Charlton Howard, Justin Bieber, Charlie Puth, Blake Slatkin	N/A	Stay	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961669/The_Kid_LAROI_Justin_Bieber_-_STAY_Official_Video_ca5nxm.mp3	N/A	N/A	Pop	The Kid LAROI, Justin Bieber
144	\N	AP Dhillon, Gminxr	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963389/Summer-High-English_y8ngxg.jpg	AP Dhillon	N/A	Summer High	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779895568/Summer_High_-_Ap_Dhillon_320_Kbps_sczapc.mp3	N/A	N/A	Punjabi Pop	AP Dhillon
145	\N	DJ Snake, Selena Gomez, Ozuna, Cardi B	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963425/Taki-Taki-English_pafnax.jpg	William Grigahcine, Juan Carlos Ozuna Rosado, Belcalis Almanzar, Selena Gomez	N/A	Taki Taki	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779896445/DJ_Snake_-_Taki_Taki_ft._Selena_Gomez_Ozuna_Cardi_B_Official_Music_Video_k7fv50.m4a	N/A	N/A	Latin Pop	DJ Snake, Selena Gomez, Ozuna, Cardi B
146	\N	Salim-Sulaiman	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963414/tauba-tauba_vdfxsm.jpg	Shabbir Ahmed	Kaal	Tauba Tauba	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779897100/Tauba_Tauba_Kaal.mp3	John Abraham, Vivek Oberoi	Lara Dutta, Esha Deol	Bollywood Pop	Richa Sharma, Sonu Nigam
155	\N	Ravi	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769962541/ye_raatein_ye_mausam_bf13th.jpg	Shailendra	Dilli Ka Thug (Cover)	Ye Raatein Ye Mausam (Cover)	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961440/Yeh-Raaten-Yeh-Mausam-Sanam-Puri-Simran-Sehgal_knta5a.mp3	Kishore Kumar	Nutan	Romantic	Sanam Band
156	\N	Andrew Taggart, Shaun Frank, Frederic Kennett, Halsey	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963177/Closer_swfvzg.jpg	Andrew Taggart, Halsey, Shaun Frank, Freddy Kennett	Collage (2016)	Closer	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779877758/Closer-_PagalSongs.Com.IN_q9722f.mp3	The Chainsmokers	Halsey	English	The Chainsmokers feat. Halsey
157	\N	Frank Ocean, Malay, Om'Mas Keith	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963173/Godspeed_yn40ak.jpg	Frank Ocean, Malay, Om'Mas Keith	Blonde (2016)	Godspeed	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769962070/Camila_Cabello_-_GODSPEED_Official_Music_Video_alksg8.mp3	Frank Ocean	\N	English	Frank Ocean
158	\N	DJ Snake, Justin Bieber, Ali Tamposi, Andrew Watt, Brian Lee, Louis Bell	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963171/let_me_love_you_g9t8kt.jpg	Justin Bieber, Ali Tamposi, Andrew Watt, Brian Lee	Encore (2016)	Let Me Love You	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779877984/Let_Me_Love_You_320_PagalWorld.com.so_hlgote.mp3	DJ Snake	Justin Bieber	English	DJ Snake feat. Justin Bieber
159	\N	Taylor Swift	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963166/love_story_xrutms.jpg	Taylor Swift	Fearless (2008)	Love Story	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779878040/Love-Story_PagalNew.Com.Se_tdlrrr.mp3	Taylor Swift	\N	English	Taylor Swift
160	\N	Taylor Swift	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963163/lover_lnatuv.jpg	Taylor Swift	Lover (2019)	Lover	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769962060/Taylor_Swift_-_Lover_Official_Music_Video_wzqqcl.mp3	Taylor Swift	\N	English	Taylor Swift
161	\N	Taylor Swift, Jack Antonoff	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779878566/Paper_rings_wu0u96.jpg	Taylor Swift, Jack Antonoff	Lover (2019)	Paper Rings	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769962065/Taylor_Swift_-_Paper_Rings_Official_Audio_s0ln8c.mp3	Taylor Swift	\N	English	Taylor Swift
148	\N	Goher Mumtaz	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779910067/musiverse/covers/pet15bjogbwkeil6fvvd.jpg	Sayeed Quadri	Kalyug	Aadat	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968134/Aadat_1_bzwx2v.mp3	Kunal Khemu	Smiley Suri	Romantic	Atif Aslam
149	\N	Pritam	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779910070/musiverse/covers/dvwfx4omrrzat6s2albf.jpg	Irshad Kamil	Jab We Met	Aao Milo Chalein	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968142/Aao_Milo_Chalo_zfaqh3.mp3	Shahid Kapoor	Kareena Kapoor	Romantic	Shaan, Ustad Sultan Khan
150	\N	Mithoon	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779910074/musiverse/covers/cnbanfuvutcsyp8akej0.jpg	Sayeed Quadri	The Train	Beete Lamhein	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968148/Beete_Lamhein_ssc4iu.mp3	Emraan Hashmi	Geeta Basra	Romantic	KK
151	\N	Harshit Saxena	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779910077/musiverse/covers/mei2mdsfyyzew7tiamcr.jpg	Sayeed Quadri	Murder 2	Hale Dil	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968359/Hale_Dil_-_Murder_2_320_Kbps_xvfypk.mp3	Emraan Hashmi	Jacqueline Fernandez	Romantic	Harshit Saxena
152	\N	Sharib-Toshi	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779910080/musiverse/covers/lujxjliffmtzfa1vzjlv.jpg	Sayeed Quadri	Raaz: The Mystery Continues	Maahi	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968419/Maahi_-_RAAZ_-_The_Mystery_Continues_320_Kbps_ugc5p1.mp3	Emraan Hashmi, Adhyayan Suman	Kangana Ranaut	Romantic	Toshi Sabri
153	\N	Mithoon	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779910084/musiverse/covers/y7b8yoq9yrimowhxnfhv.jpg	Mithoon	Anwar	Maula Mere Maula	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968426/Maula_Mere_Maula_-_Anwar_320_Kbps_bsudkj.mp3	Siddharth Koirala	Nauheed Cyrusi	Romantic	Roop Kumar Rathod
154	\N	Pritam	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779910087/musiverse/covers/ftowpu2lp5uzvp1rksle.jpg	Sameer Anjaan	Race	Pehli Nazar Mein	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769968434/Pehli_Nazar_Mein_-_Race_320_Kbps_z4m9mn.mp3	Saif Ali Khan, Akshaye Khanna	Bipasha Basu, Katrina Kaif	Romantic	Atif Aslam
162	\N	Andrew Watt, Benny Blanco, Ali Tamposi, Camila Cabello, Shawn Mendes	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963161/Se%C3%B1orita_tjb4yl.jpg	Ali Tamposi, Camila Cabello, Shawn Mendes, Andrew Watt, Benny Blanco	Shawn Mendes (Deluxe) (2019)	Señorita	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779878085/Senorita-Ringtone---Shawn-Mendes-Version_PagalWorld_d5clbj.mp3	Shawn Mendes	Camila Cabello	English	Shawn Mendes & Camila Cabello
163	\N	Taylor Swift, Liz Rose	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963158/you_belong_with_me_cfnebr.jpg	Taylor Swift, Liz Rose	Fearless (2008)	You Belong with Me	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779878129/You-Belong-With-Me_320_PagalWorld_hrjpoi.mp3	Taylor Swift	\N	English	Taylor Swift
164	\N	Shankar-Ehsaan-Loy	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963922/Dil_dhadakne_do_kz0ige.jpg	Javed Akhtar	Dil Dhadakne Do	Dil Dhadakne Do	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779880338/Dil_Dhadakne_Do_-_Zindagi_Na_Milegi_Dobara_320_Kbps_nmk23c.mp3	Ranveer Singh, Anil Kapoor	Priyanka Chopra, Anushka Sharma	Hindi	Farhan Akhtar, Priyanka Chopra, Shankar Mahadevan, Yashita Sharma
165	\N	Vishal-Shekhar	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963916/Dil_diyan_gallan_siokkw.jpg	Irshad Kamil	Tiger Zinda Hai	Dil Diyan Gallan	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779880362/Dil_Diyan_Gallan_-_Tiger_Zinda_Hai_320_Kbps_byi66f.mp3	Salman Khan	Katrina Kaif	Hindi	Atif Aslam
166	\N	Shankar-Ehsaan-Loy	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963924/Gallan_goodiyan_aqojmf.jpg	Javed Akhtar	Dil Dhadakne Do	Gallan Goodiyan	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779880334/Gallan_Goodiyaan_-_Dil_Dhadakne_Do_320_Kbps_qw4htl.mp3	Ranveer Singh, Anil Kapoor	Priyanka Chopra, Anushka Sharma	Hindi	Farhan Akhtar, Shankar Mahadevan, Yashita Sharma
167	\N	Badshah	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963927/Kala_chashma_o54mp5.jpg	Amrik Singh, Kumaar	Baar Baar Dekho	Kala Chashma	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779880330/Kala_Chashma_lpr2gh.mp3	Sidharth Malhotra	Katrina Kaif	Hindi	Badshah, Neha Kakkar, Amar Arshi
168	\N	Badshah, Amaal Mallik	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963930/Kar_gayi_chull_o4xggc.jpg	Badshah, Kumaar	Kapoor & Sons	Kar Gayi Chull	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779880327/Kar_Gayi_Chull_-_Kapoor_And_Sons_Since_1921_320_Kbps_rpqw5d.mp3	Sidharth Malhotra	Alia Bhatt	Hindi	Badshah, Neha Kakkar
169	\N	Amit Trivedi	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963908/London_thumakda_fa8isi.jpg	Anvita Dutt	Queen	London Thumakda	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779880321/London_Thumakda_-_Queen_320_Kbps_kwov1q.mp3	Rajkummar Rao	Kangana Ranaut	Hindi	Labh Janjua, Sonu Kakkar, Neha Kakkar
170	\N	Yo Yo Honey Singh	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963913/Lungi_dance_o6kood.jpg	Yo Yo Honey Singh	Chennai Express	Lungi Dance	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1769961977/Lungi-Dance-Yo-Yo-Honey-Singh_x12unz.mp3	Shah Rukh Khan	Deepika Padukone	Hindi	Yo Yo Honey Singh
171	\N	Jeet Gannguli	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963910/O_maahi_dqvcg5.jpg	Kausar Munir	Raaz: Reboot	O Maahi	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779880315/O_Mahi_O_Mahi_320_PagalWorld.com.sb_hiz4oa.mp3	Emraan Hashmi	Kriti Kharbanda	Hindi	Arijit Singh
172	\N	Pritam	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963902/Pee_loon_asxh1q.jpg	Irshad Kamil	Once Upon a Time in Mumbaai	Pee Loon	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779880307/Pee_Loon_Hoto_Ki_Sargam_-_Once_Upon_A_Time_In_Mumbaai_320_Kbps_jnjoak.mp3	Emraan Hashmi	Prachi Desai	Hindi	Mohit Chauhan
173	\N	Jasleen Royal	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963905/sang_rahiyo_jwdyey.jpg	Neeraj Rajawat	N/A	Sang Rahiyo	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779880290/Sang-Rahiyo_Pagal-World.Com.In_pughsj.mp3	Rajkummar Rao	Patralekha	Hindi	Jasleen Royal
174	\N	Vishal-Shekhar	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963899/The_disco_song_faapo1.jpg	Anvita Dutt	Student of the Year	The Disco Song	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779880283/The_Disco_Song_-_Student_Of_The_Year_320_Kbps_mwzaij.mp3	Varun Dhawan, Sidharth Malhotra	Alia Bhatt	Hindi	Benny Dayal, Sunidhi Chauhan
175	\N	Pritam	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1769963896/Ve_kamleya_pvaghm.jpg	Amitabh Bhattacharya	Rocky Aur Rani Kii Prem Kahani	Ve Kamleya	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779880287/Ve_Kamleya_-_Rocky_Aur_Rani_Kii_Prem_Kahaani_320_Kbps_volfss.mp3	Ranveer Singh	Alia Bhatt	Hindi	Arijit Singh, Shreya Ghoshal
176	\N	JAM8	https://res.cloudinary.com/dzh4n8fxx/image/upload/v1779880056/zaalima_loxxvc.jpg	Amitabh Bhattacharya	Raees	Zaalima	https://res.cloudinary.com/dzh4n8fxx/video/upload/v1779880311/O-Zaalima-o-Zaalima_PagalWorlld.Com_a7gt3w.mp3	Shah Rukh Khan	Mahira Khan	Hindi	Arijit Singh, Harshdeep Kaur
\.


--
-- Data for Name: user_hidden_songs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_hidden_songs (user_id, song_id) FROM stdin;
8	2
\.


--
-- Data for Name: user_liked_songs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_liked_songs (user_id, song_id) FROM stdin;
8	6
8	107
8	108
8	101
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, name, email, password, role, created_at) FROM stdin;
1	Zainab	zainab@test.com	123456	USER	2026-02-03 00:31:39.347057
2	Zainab	zainab2@test.com	123456	USER	2026-02-03 00:35:23.850787
3	Zainab	zainab2005@test.com	123456	USER	2026-02-03 01:14:27.977076
4	Zainab	zainab_new2@test.com	123456	USER	2026-02-03 01:24:33.290265
5	Zainab	zainab.shaikh132005@gmail.com	$2a$10$LcZD1AD1blLbP7PCa7j/JOY/tALFUbkPKOc4OomMKBiJa/Dw0ymlu	USER	2026-03-04 00:34:55.572282
6	Test User	test@musiverse.com	$2a$10$P95UiemJylPrOhYHfurlLuuSO6AqBQLoH0QuHJPpbdAVDqT4zMrbm	USER	2026-04-15 22:33:06.06389
7	Demo	demo@musiverse.com	$2a$10$DruoQiLgRfXBZdDdaHla9up8ywiTwdxKB347y89eCLtCw9qcD18oO	USER	2026-04-15 22:44:33.695936
8	zainab	ztest4b@gmail.com	$2a$10$HR1YKV/iwuJ1OsKersXyvuOvJISAO4gUwxeD55pno6pFYWs5AyvM6	USER	2026-05-27 23:11:56.39949
\.


--
-- Name: songs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.songs_id_seq', 176, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 8, true);


--
-- Name: songs songs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.songs
    ADD CONSTRAINT songs_pkey PRIMARY KEY (id);


--
-- Name: user_hidden_songs user_hidden_songs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_hidden_songs
    ADD CONSTRAINT user_hidden_songs_pkey PRIMARY KEY (user_id, song_id);


--
-- Name: user_liked_songs user_liked_songs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_liked_songs
    ADD CONSTRAINT user_liked_songs_pkey PRIMARY KEY (user_id, song_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: user_liked_songs fk2nvwsqy7sacxpfmck0grt43bk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_liked_songs
    ADD CONSTRAINT fk2nvwsqy7sacxpfmck0grt43bk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_liked_songs fk6olgdy1fud5s9fc0mnewytfd0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_liked_songs
    ADD CONSTRAINT fk6olgdy1fud5s9fc0mnewytfd0 FOREIGN KEY (song_id) REFERENCES public.songs(id);


--
-- Name: user_hidden_songs fk75c0rdhb63qt2aier4elrhxj4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_hidden_songs
    ADD CONSTRAINT fk75c0rdhb63qt2aier4elrhxj4 FOREIGN KEY (song_id) REFERENCES public.songs(id);


--
-- Name: user_hidden_songs fkmy7393dfdgicyyaqh7ohw4q9q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_hidden_songs
    ADD CONSTRAINT fkmy7393dfdgicyyaqh7ohw4q9q FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict MWbaiUgUwdGAFuLwIKImFTDDqA7ZzS80fCAWHCyeEGgQP8PdYYaFyhYgfDhtB93

